CREATE DATABASE SkyTrack

CREATE TABLE AIRPORT( 
AirportID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
IATA_CODE VARCHAR(50) UNIQUE NOT NULL,
Name VARCHAR(30) NOT NULL, 
City VARCHAR(15) NOT NULL,
Country VARCHAR(20) NOT NULL
);

CREATE TABLE AIRCRAFT( 
AIRCRAFTID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
REGNO VARCHAR(30) NOT NULL UNIQUE,
Model VARCHAR(20) NOT NULL,
Manufacturer VARCHAR(20) NOT NULL,
YearOfManufature VARCHAR(5),
Capacity INT NOT NULL CHECK (Capacity > 0)
);

CREATE TABLE FLIGHT(
FLIGHTID INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
FlightNO VARCHAR(30) NOT NULL UNIQUE,
Status VARCHAR(12) NOT NULL DEFAULT 'Scheduled' CHECK (Status IN ('Scheduled','Delayed','Cancelled','Completed')), 
DepartureDateTime VARCHAR(30) NOT NULL,
ArrivalDateTIME VARCHAR(30) NOT NULL,
DepAirportID VARCHAR(50),
ArrAirportID VARCHAR(50),
AircraftID VARCHAR(30),
FOREIGN KEY (DepAirportID) REFERENCES AIRPORT(IATA_CODE)
ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY (ArrAirportID) REFERENCES AIRPORT(IATA_CODE)
ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY (AircraftID) REFERENCES AIRCRAFT(REGNO)
ON DELETE CASCADE ON UPDATE CASCADE,

CONSTRAINT CK_Flight_Times CHECK (ArrivalDateTime > DepartureDateTime)
);

CREATE TABLE PASSENGER(
PassengerID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NationalID VARCHAR(15) NOT NULL UNIQUE,
Fname VARCHAR(20) NOT NULL,
Lname VARCHAR(20) NOT NULL,
Nationality VARCHAR(20) NOT NULL,
DOB DATE NOT NULL,
PHONE VARCHAR(15) NULL,
EMAIL VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE BOOKING(
BOOKINGID INT IDENTITY(1,1) PRIMARY KEY,
Class VARCHAR(20) NOT NULL CHECK (Class IN( 'Economy', 'Business', 'First')),
Price DECIMAL(10,2) NOT NULL CHECK (Price > 0),
SeatNO VARCHAR(15) NOT NULL,
BookingDate DATE NOT NULL DEFAULT GETDATE(),
FlightID INT NOT NULL,
PassengerID VARCHAR(15) NOT NULL,
FOREIGN KEY (FlightID) REFERENCES FLIGHT(FLIGHTID)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (PassengerID) REFERENCES PASSENGER(NationalID)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CREWMEMBER(
CREWMEMBERID INT IDENTITY(1,1) PRIMARY KEY,
LicenseNO VARCHAR(20) NOT NULL UNIQUE,
Fname VARCHAR(20) NOT NULL,
Lname VARCHAR(20) NOT NULL,
Role VARCHAR(30) NOT NULL CHECK (Role IN('Pilot', 'Co-Pilot', 'Flight Attendant', 'Engineer'))
);

CREATE TABLE FLIGHTCREW(
LicenseNO VARCHAR(20) NOT NULL,
FLIGHTID INT NOT NULL ,
PRIMARY KEY(LicenseNO, FLIGHTID),
FOREIGN KEY (LicenseNO) REFERENCES CREWMEMBER(LicenseNO)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (FLIGHTID) REFERENCES FLIGHT(FLIGHTID)
ON DELETE CASCADE ON UPDATE CASCADE
);
